edition="2021"
hard_tabs  = true
max_width = 100
use_small_heuristics = "Max"

imports_granularity = "Crate"
reorder_imports = true

newline_style = "Unix"

chain_width = 80
spaces_around_ranges = false
binop_separator = "Back"
reorder_impl_items = false
match_arm_leading_pipes = "Preserve"
match_arm_blocks = false
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true

commend_width=100